[package]
name = "asc-rs"
version = "0.1.0"
edition = "2024"
description = "A Rust rewrite of Droid ASC's APK/DEX query CLI"
license = "MIT"

[dependencies]
aho-corasick = "1"
anyhow = "1"
adler2 = "2"
axml-parser = { git = "https://github.com/androguard/axml-parser.git", rev = "dfca90754f0b6933060fd0eaa85720bed58160c1" }
clap = { version = "4", features = ["derive"] }
dex-decompiler = { git = "https://github.com/androguard/dex-decompiler.git", rev = "7345cac29985e0536d6105a65ac5c22e2fe6507f" }
flate2 = { version = "1", default-features = false, features = ["zlib"] }
memmap2 = "0.9"
rayon = "1"
serde_json = "1"
sha1 = "0.10"
tempfile = "3"
zip = { version = "0.6", default-features = false, features = ["deflate-zlib"] }

[profile.release]
strip = true
